2023-05-24 15:17:13,931 ERROR: Exception on /subscribe/28 [POST] [in /Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/sync.py", line 117, in populate_dict
    value = source_mapper._get_state_attr_by_column(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/mapper.py", line 3559, in _get_state_attr_by_column
    prop = self._columntoproperty[column]
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/mapper.py", line 4330, in __missing__
    raise orm_exc.UnmappedColumnError(
sqlalchemy.orm.exc.UnmappedColumnError: No column user.id is configured on mapper Mapper[Post(post)]...

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smirsepahi/Documents/Code/Event-It/app/routes.py", line 190, in subscribe
    db.session.commit()
  File "/Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/scoping.py", line 538, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1903, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1218, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1193, in _prepare_impl
    self.session.flush()
  File "/Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4140, in flush
    self._flush(objects)
  File "/Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4276, in _flush
    with util.safe_reraise():
  File "/Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4237, in _flush
    flush_context.execute()
  File "/Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 467, in execute
    rec.execute(self)
  File "/Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 593, in execute
    self.dependency_processor.process_saves(uow, states)
  File "/Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/dependency.py", line 1140, in process_saves
    if not self._synchronize(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/dependency.py", line 1272, in _synchronize
    sync.populate_dict(
  File "/Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/sync.py", line 121, in populate_dict
    _raise_col_to_prop(False, source_mapper, l, None, r, err)
  File "/Users/smirsepahi/Documents/Code/microblog/venv/lib/python3.11/site-packages/sqlalchemy/orm/sync.py", line 157, in _raise_col_to_prop
    raise exc.UnmappedColumnError(
sqlalchemy.orm.exc.UnmappedColumnError: Can't execute sync rule for source column 'user.id'; mapper 'Mapper[Post(post)]' does not map this column.  Try using an explicit `foreign_keys` collection which does not include destination column 'subscribers.subscribed_id' (or use a viewonly=True relation).
2023-05-24 15:18:58,300 INFO: Microblog startup [in /Users/smirsepahi/Documents/Code/Event-It/app/__init__.py:45]
2023-05-24 15:19:05,277 INFO: Microblog startup [in /Users/smirsepahi/Documents/Code/Event-It/app/__init__.py:45]
2023-05-24 15:19:09,247 INFO: Microblog startup [in /Users/smirsepahi/Documents/Code/Event-It/app/__init__.py:45]
2023-05-24 15:19:12,134 INFO: Microblog startup [in /Users/smirsepahi/Documents/Code/Event-It/app/__init__.py:45]
